### ISSUE TITLE
Error when running cnn.py with an image

### ISSUE THREAD

**Issue by szaman19** [AvocadosConstant/phytoplankton-classification#2]
The following error pops up when trying to predict a single image. Seems like a problem with the graph loading but unsure. 
```Traceback (most recent call last):
  File "cnn.py", line 53, in <module>
    result=sess.run(y_pred, feed_dict=feed_dict_testing)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow/python/client/session.py", line 1116, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 2) for Tensor 'y_true:0', which has shape '(?, 10)```

**Comment by szaman19** [comment]
Issue fixed. The prediction vector must be initialized with the correct number of classes.
